sonar.projectKey=PRUEBAS-ESTATICAS-2026-ESPACIOS-BOLIVIA
sonar.projectName=PRUEBAS ESTATICAS 2026 ESPACIOS BOLIVIA
sonar.projectVersion=1.0

sonar.sources=EspaciosBolivia-master
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token = sqp_6167ecfaa3b44e7c10bf71f83fdc0691a0218792