sonar.projectKey=PRUEBAS-ESTATICAS-2026-ESPACIOS-BOLIVIA
sonar.projectName=PRUEBAS ESTATICAS 2026 ESPACIOS BOLIVIA
sonar.projectVersion=1.0

sonar.sources=EspaciosBolivia-master
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.angular/**,**/.scannerwork/**,**/coverage/**,**/package-lock.json,**/src/assets/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
